name: Build regex_toolkit
description: Build regex_toolkit
runs:
  using: composite
  steps:
    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
      shell: bash -el {0}

    - name: Build Regex-Toolkit
      run: |
        python -m pip install -e . --no-build-isolation --no-index
      shell: bash -el {0}
