name: "Stale PRs"
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "This pull request is stale because it has been open for thirty days with no activity. Please update and respond to this comment if you're still interested in working on this."
          stale-pr-label: "Stale"
          exempt-pr-labels: "Needs Review,Blocked,Needs Discussion"
          days-before-issue-stale: -1
          days-before-pr-stale: 30
          days-before-close: -1
          remove-stale-when-updated: false
          debug-only: false
