name: Ubuntu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

env:
  REGEX_TOOLKIT_CI: 1

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -el {0}
    timeout-minutes: 60
    strategy:
      matrix:
        python_version: ['310', '311', '312']
      fail-fast: false
    name: Python ${{ matrix.python_version }}
    env:
      ENV_FILE: ci/deps/actions-${{ matrix.python_version }}.yml
      IS_PYPY: ${{ contains(matrix.python_version, 'pypy') }}
    concurrency:
      # https://github.community/t/concurrecy-not-work-for-push/183068/7
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ matrix.python_version }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Conda
        uses: ./.github/actions/setup-conda
        with:
          environment-name: ${{ matrix.python_version }}-env
          environment-file: ${{ env.ENV_FILE }}

      - name: Build Regex-Toolkit
        uses: ./.github/actions/build_regex_toolkit

      - name: Test
        uses: ./.github/actions/run-tests
        with:
          python-version: ${{ matrix.python_version }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
